### PR TITLE
Add support arm64

### PR DESCRIPTION
**Pull request by ma-sadeghi**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ma-sadeghi** [comment]
Hi @conda-forge/help-osx-arm64, could you please look into this PR and check if the changes I made are sufficient? Much appreciate it!

**Review by jaimergp — CHANGES_REQUESTED** [review]
Not necessary. This package is `noarch: python` and is already available on `osx-arm64`:

```
$ conda create -n openpnm openpnm --dry-run
Channels:
 - conda-forge
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/jrodriguez/.local/anaconda/envs/openpnm

  added / updated specs:
    - openpnm


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    blosc-1.21.5               |       hc338f07_0          33 KB  conda-forge
    brotli-1.1.0               |       hb547adb_1          19 KB  conda-forge
    brotli-bin-1.1.0           |       hb547adb_1          17 KB  conda-forge
    c-blosc2-2.10.4            |       h068da5f_0         237 KB  conda-forge
    cached-property-1.5.2      |       hd8ed1ab_1           4 KB  conda-forge
    cached_property-1.5.2      |     pyha770c72_1          11 KB  conda-forge
    charls-2.4.2               |       h13dd4ca_0         114 KB  conda-forge
    contourpy-1.1.1            |  py311he4fd1f5_1         223 KB  conda-forge
    dav1d-1.2.1                |       hb547adb_0         309 KB  conda-forge
    docrep-0.3.2               |     pyh44b312d_0          19 KB  conda-forge
    flatdict-4.0.1             |     pyh9f0ad1d_0          10 KB  conda-forge
    fonttools-4.43.0           |  py311heffc1b2_0         2.6 MB  conda-forge
    gitpython-3.1.37           |     pyhd8ed1ab_0         144 KB  conda-forge
    gmpy2-2.1.2                |  py311h2ba9262_1         161 KB  conda-forge
    h5py-3.9.0                 |nompi_py311h4794d1a_103         1.1 MB  conda-forge
    hdf5-1.14.2                |nompi_h3aba7b3_100         3.3 MB  conda-forge
    imagecodecs-2023.9.18      |  py311hc277e5d_0         1.7 MB  conda-forge
    imageio-2.31.1             |     pyh24c5eb1_0         284 KB  conda-forge
    jsonschema-4.19.1          |     pyhd8ed1ab_0          69 KB  conda-forge
    kiwisolver-1.4.5           |  py311he4fd1f5_1          60 KB  conda-forge
    lazy_loader-0.3            |     pyhd8ed1ab_0          14 KB  conda-forge
    libavif16-1.0.1            |       h57fd00a_1          82 KB  conda-forge
    libbrotlicommon-1.1.0      |       hb547adb_1          67 KB  conda-forge
    libbrotlidec-1.1.0         |       hb547adb_1          28 KB  conda-forge
    libbrotlienc-1.1.0         |       hb547adb_1         274 KB  conda-forge
    llvmlite-0.40.1            |  py311hea943cd_0         325 KB  conda-forge
    matplotlib-base-3.8.0      |  py311h3bc9839_1         7.4 MB  conda-forge
    mpc-1.3.1                  |       h91ba8db_0         101 KB  conda-forge
    mpfr-4.2.0                 |       he09a6ba_0         336 KB  conda-forge
    mpmath-1.3.0               |     pyhd8ed1ab_0         428 KB  conda-forge
    numba-0.57.1               |  py311hbf3c4e2_0         5.3 MB  conda-forge
    numpy-1.24.4               |  py311hb8f3215_0         6.4 MB  conda-forge
    openpnm-2.4.2              |     pyh9f0ad1d_0         235 KB  conda-forge
    pandas-2.1.1               |  py311h9e438b8_1        13.7 MB  conda-forge
    pillow-10.0.1              |  py311he9c13d2_1        43.9 MB  conda-forge
    pthread-stubs-0.4          |    h27ca646_1001           6 KB  conda-forge
    python_abi-3.11            |          4_cp311           6 KB  conda-forge
    pywavelets-1.4.1           |  py311hb49d859_1         3.5 MB  conda-forge
    rav1e-0.6.6                |       h69fbcac_2         1.5 MB  conda-forge
    rpds-py-0.10.3             |  py311h0563b04_1         281 KB  conda-forge
    scikit-image-0.21.0        |  py311ha891d26_0        10.1 MB  conda-forge
    scipy-1.11.3               |  py311h93d07a4_0        14.5 MB  conda-forge
    svt-av1-1.7.0              |       hb765f3a_0         1.2 MB  conda-forge
    sympy-1.12                 | pypyh9d50eac_103         4.1 MB  conda-forge
    terminaltables-3.1.10      |     pyhd8ed1ab_0          16 KB  conda-forge
    tifffile-2023.9.26         |     pyhd8ed1ab_0         172 KB  conda-forge
    transforms3d-0.4.1         |     pyhd8ed1ab_0         2.6 MB  conda-forge
    unyt-2.9.5                 |     pyhd8ed1ab_0          98 KB  conda-forge
    ------------------------------------------------------------
                                           Total:       126.8 MB

The following NEW packages will be INSTALLED:

  aom                conda-forge/osx-arm64::aom-3.5.0-h7ea286d_0 
  attrs              conda-forge/noarch::attrs-23.1.0-pyh71513ae_1 
  blosc              conda-forge/osx-arm64::blosc-1.21.5-hc338f07_0 
  brotli             conda-forge/osx-arm64::brotli-1.1.0-hb547adb_1 
  brotli-bin         conda-forge/osx-arm64::brotli-bin-1.1.0-hb547adb_1 
  brunsli            conda-forge/osx-arm64::brunsli-0.1-h9f76cd9_0 
  bzip2              conda-forge/osx-arm64::bzip2-1.0.8-h3422bc3_4 
  c-ares             conda-forge/osx-arm64::c-ares-1.19.1-hb547adb_0 
  c-blosc2           conda-forge/osx-arm64::c-blosc2-2.10.4-h068da5f_0 
  ca-certificates    conda-forge/osx-arm64::ca-certificates-2023.7.22-hf0a4a13_0 
  cached-property    conda-forge/noarch::cached-property-1.5.2-hd8ed1ab_1 
  cached_property    conda-forge/noarch::cached_property-1.5.2-pyha770c72_1 
  certifi            conda-forge/noarch::certifi-2023.7.22-pyhd8ed1ab_0 
  charls             conda-forge/osx-arm64::charls-2.4.2-h13dd4ca_0 
  contourpy          conda-forge/osx-arm64::contourpy-1.1.1-py311he4fd1f5_1 
  cycler             conda-forge/noarch::cycler-0.11.0-pyhd8ed1ab_0 
  dav1d              conda-forge/osx-arm64::dav1d-1.2.1-hb547adb_0 
  docrep             conda-forge/noarch::docrep-0.3.2-pyh44b312d_0 
  flatdict           conda-forge/noarch::flatdict-4.0.1-pyh9f0ad1d_0 
  fonttools          conda-forge/osx-arm64::fonttools-4.43.0-py311heffc1b2_0 
  freetype           conda-forge/osx-arm64::freetype-2.12.1-hadb7bae_2 
  giflib             conda-forge/osx-arm64::giflib-5.2.1-h1a8c8d9_3 
  gitdb              conda-forge/noarch::gitdb-4.0.10-pyhd8ed1ab_0 
  gitpython          conda-forge/noarch::gitpython-3.1.37-pyhd8ed1ab_0 
  gmp                conda-forge/osx-arm64::gmp-6.2.1-h9f76cd9_0 
  gmpy2              conda-forge/osx-arm64::gmpy2-2.1.2-py311h2ba9262_1 
  h5py               conda-forge/osx-arm64::h5py-3.9.0-nompi_py311h4794d1a_103 
  hdf5               conda-forge/osx-arm64::hdf5-1.14.2-nompi_h3aba7b3_100 
  imagecodecs        conda-forge/osx-arm64::imagecodecs-2023.9.18-py311hc277e5d_0 
  imageio            conda-forge/noarch::imageio-2.31.1-pyh24c5eb1_0 
  importlib_resourc~ conda-forge/noarch::importlib_resources-6.1.0-pyhd8ed1ab_0 
  jsonschema         conda-forge/noarch::jsonschema-4.19.1-pyhd8ed1ab_0 
  jsonschema-specif~ conda-forge/noarch::jsonschema-specifications-2023.7.1-pyhd8ed1ab_0 
  jxrlib             conda-forge/osx-arm64::jxrlib-1.1-h27ca646_2 
  kiwisolver         conda-forge/osx-arm64::kiwisolver-1.4.5-py311he4fd1f5_1 
  krb5               conda-forge/osx-arm64::krb5-1.21.2-h92f50d5_0 
  lazy_loader        conda-forge/noarch::lazy_loader-0.3-pyhd8ed1ab_0 
  lcms2              conda-forge/osx-arm64::lcms2-2.15-h40e5a24_2 
  lerc               conda-forge/osx-arm64::lerc-4.0.0-h9a09cb3_0 
  libaec             conda-forge/osx-arm64::libaec-1.0.6-hb7217d7_1 
  libavif16          conda-forge/osx-arm64::libavif16-1.0.1-h57fd00a_1 
  libblas            conda-forge/osx-arm64::libblas-3.9.0-18_osxarm64_openblas 
  libbrotlicommon    conda-forge/osx-arm64::libbrotlicommon-1.1.0-hb547adb_1 
  libbrotlidec       conda-forge/osx-arm64::libbrotlidec-1.1.0-hb547adb_1 
  libbrotlienc       conda-forge/osx-arm64::libbrotlienc-1.1.0-hb547adb_1 
  libcblas           conda-forge/osx-arm64::libcblas-3.9.0-18_osxarm64_openblas 
  libcurl            conda-forge/osx-arm64::libcurl-8.3.0-hc52a3a8_0 
  libcxx             conda-forge/osx-arm64::libcxx-16.0.6-h4653b0c_0 
  libdeflate         conda-forge/osx-arm64::libdeflate-1.19-hb547adb_0 
  libedit            conda-forge/osx-arm64::libedit-3.1.20191231-hc8eb9b7_2 
  libev              conda-forge/osx-arm64::libev-4.33-h642e427_1 
  libexpat           conda-forge/osx-arm64::libexpat-2.5.0-hb7217d7_1 
  libffi             conda-forge/osx-arm64::libffi-3.4.2-h3422bc3_5 
  libgfortran        conda-forge/osx-arm64::libgfortran-5.0.0-13_2_0_hd922786_1 
  libgfortran5       conda-forge/osx-arm64::libgfortran5-13.2.0-hf226fd6_1 
  libjpeg-turbo      conda-forge/osx-arm64::libjpeg-turbo-2.1.5.1-hb547adb_1 
  liblapack          conda-forge/osx-arm64::liblapack-3.9.0-18_osxarm64_openblas 
  libllvm14          conda-forge/osx-arm64::libllvm14-14.0.6-hd1a9a77_4 
  libnghttp2         conda-forge/osx-arm64::libnghttp2-1.52.0-hae82a92_0 
  libopenblas        conda-forge/osx-arm64::libopenblas-0.3.24-openmp_hd76b1f2_0 
  libpng             conda-forge/osx-arm64::libpng-1.6.39-h76d750c_0 
  libsqlite          conda-forge/osx-arm64::libsqlite-3.43.0-hb31c410_0 
  libssh2            conda-forge/osx-arm64::libssh2-1.11.0-h7a5bd25_0 
  libtiff            conda-forge/osx-arm64::libtiff-4.6.0-h77c4dce_1 
  libwebp-base       conda-forge/osx-arm64::libwebp-base-1.3.2-hb547adb_0 
  libxcb             conda-forge/osx-arm64::libxcb-1.15-hf346824_0 
  libzlib            conda-forge/osx-arm64::libzlib-1.2.13-h53f4e23_5 
  libzopfli          conda-forge/osx-arm64::libzopfli-1.0.3-h9f76cd9_0 
  llvm-openmp        conda-forge/osx-arm64::llvm-openmp-16.0.6-h1c12783_0 
  llvmlite           conda-forge/osx-arm64::llvmlite-0.40.1-py311hea943cd_0 
  lz4-c              conda-forge/osx-arm64::lz4-c-1.9.4-hb7217d7_0 
  matplotlib-base    conda-forge/osx-arm64::matplotlib-base-3.8.0-py311h3bc9839_1 
  mpc                conda-forge/osx-arm64::mpc-1.3.1-h91ba8db_0 
  mpfr               conda-forge/osx-arm64::mpfr-4.2.0-he09a6ba_0 
  mpmath             conda-forge/noarch::mpmath-1.3.0-pyhd8ed1ab_0 
  munkres            conda-forge/noarch::munkres-1.1.4-pyh9f0ad1d_0 
  ncurses            conda-forge/osx-arm64::ncurses-6.4-h7ea286d_0 
  networkx           conda-forge/noarch::networkx-3.1-pyhd8ed1ab_0 
  numba              conda-forge/osx-arm64::numba-0.57.1-py311hbf3c4e2_0 
  numpy              conda-forge/osx-arm64::numpy-1.24.4-py311hb8f3215_0 
  openjpeg           conda-forge/osx-arm64::openjpeg-2.5.0-h4c1507b_3 
  openpnm            conda-forge/noarch::openpnm-2.4.2-pyh9f0ad1d_0 
  openssl            conda-forge/osx-arm64::openssl-3.1.3-h53f4e23_0 
  packaging          conda-forge/noarch::packaging-23.1-pyhd8ed1ab_0 
  pandas             conda-forge/osx-arm64::pandas-2.1.1-py311h9e438b8_1 
  pillow             conda-forge/osx-arm64::pillow-10.0.1-py311he9c13d2_1 
  pkgutil-resolve-n~ conda-forge/noarch::pkgutil-resolve-name-1.3.10-pyhd8ed1ab_1 
  pthread-stubs      conda-forge/osx-arm64::pthread-stubs-0.4-h27ca646_1001 
  pyparsing          conda-forge/noarch::pyparsing-3.1.1-pyhd8ed1ab_0 
  python             conda-forge/osx-arm64::python-3.11.5-h47c9636_0_cpython 
  python-dateutil    conda-forge/noarch::python-dateutil-2.8.2-pyhd8ed1ab_0 
  python-tzdata      conda-forge/noarch::python-tzdata-2023.3-pyhd8ed1ab_0 
  python_abi         conda-forge/osx-arm64::python_abi-3.11-4_cp311 
  pytz               conda-forge/noarch::pytz-2023.3.post1-pyhd8ed1ab_0 
  pywavelets         conda-forge/osx-arm64::pywavelets-1.4.1-py311hb49d859_1 
  rav1e              conda-forge/osx-arm64::rav1e-0.6.6-h69fbcac_2 
  readline           conda-forge/osx-arm64::readline-8.2-h92ec313_1 
  referencing        conda-forge/noarch::referencing-0.30.2-pyhd8ed1ab_0 
  rpds-py            conda-forge/osx-arm64::rpds-py-0.10.3-py311h0563b04_1 
  scikit-image       conda-forge/osx-arm64::scikit-image-0.21.0-py311ha891d26_0 
  scipy              conda-forge/osx-arm64::scipy-1.11.3-py311h93d07a4_0 
  six                conda-forge/noarch::six-1.16.0-pyh6c4a22f_0 
  smmap              conda-forge/noarch::smmap-3.0.5-pyh44b312d_0 
  snappy             conda-forge/osx-arm64::snappy-1.1.10-h17c5cce_0 
  svt-av1            conda-forge/osx-arm64::svt-av1-1.7.0-hb765f3a_0 
  sympy              conda-forge/noarch::sympy-1.12-pypyh9d50eac_103 
  terminaltables     conda-forge/noarch::terminaltables-3.1.10-pyhd8ed1ab_0 
  tifffile           conda-forge/noarch::tifffile-2023.9.26-pyhd8ed1ab_0 
  tk                 conda-forge/osx-arm64::tk-8.6.13-hb31c410_0 
  transforms3d       conda-forge/noarch::transforms3d-0.4.1-pyhd8ed1ab_0 
  typing_extensions  conda-forge/noarch::typing_extensions-4.8.0-pyha770c72_0 
  tzdata             conda-forge/noarch::tzdata-2023c-h71feb2d_0 
  unyt               conda-forge/noarch::unyt-2.9.5-pyhd8ed1ab_0 
  xorg-libxau        conda-forge/osx-arm64::xorg-libxau-1.0.11-hb547adb_0 
  xorg-libxdmcp      conda-forge/osx-arm64::xorg-libxdmcp-1.1.3-h27ca646_0 
  xz                 conda-forge/osx-arm64::xz-5.2.6-h57fd34a_0 
  zfp                conda-forge/osx-arm64::zfp-1.0.0-hb6e4faa_3 
  zipp               conda-forge/noarch::zipp-3.17.0-pyhd8ed1ab_0 
  zlib-ng            conda-forge/osx-arm64::zlib-ng-2.0.7-h1a8c8d9_0 
  zstd               conda-forge/osx-arm64::zstd-1.5.5-h4f39d0f_0 



DryRunExit: Dry run. Exiting.
```

**Comment by ma-sadeghi** [comment]
@jaimergp Thanks. One issue though: the openpnm version in your logs shows 2.4.2, but the latest is 3.2.1. Is there a way to force the latest build?

**Comment by ma-sadeghi** [comment]
> @jaimergp Thanks. One issue though: the openpnm version in your logs shows 2.4.2, but the latest is 3.2.1. Is there a way to force the latest build?

The problem is `pypardiso` (probably?) which is not availale on ARM64 architecture.

**Pull request closed without merging**
